/*
 * Read, save, and restore IRQ flags.
 * Since the FLAGS register changes word size on different architectures (duh),
 * this is split between x86_64 and i386
 */
#ifndef IRQ_FLAGS_H
#define IRQ_FLAGS_H

// RFLAGS bits, generated by clod:

/* Intel SDM Vol. 1, §3.4.3 */
/* Status flags — written by arithmetic/logic instructions */
#define FL_CF 0x00000001 /* bit  0: carry — unsigned overflow/borrow      */
/*         also the result bit of bt/bts/btr     */
#define FL_RESERVED1 \
	0x00000002 /* bit  1: reserved, always reads 1              */
#define FL_PF 0x00000004 /* bit  2: parity — even # of set bits in low 8  */
#define FL_AF 0x00000010 /* bit  4: adjust — carry out of bit 3, for BCD  */
#define FL_ZF 0x00000040 /* bit  6: zero — result was 0                   */
#define FL_SF 0x00000080 /* bit  7: sign — copy of the result's high bit  */
#define FL_OF 0x00000800 /* bit 11: overflow — signed overflow            */

/* Control flags */
#define FL_TF 0x00000100 /* bit  8: trap — raise #DB after every instr;   */
/*         this is how single-stepping works     */
#define FL_IF 0x00000200 /* bit  9: interrupt enable — sti sets, cli      */
/*         clears. Maskable IRQs only.           */
#define FL_DF 0x00000400 /* bit 10: direction — 1 = string ops (movs,     */
/*         stos) walk downward. cld before use.  */

/* System flags */
#define FL_IOPL 0x00003000 /* bits 12-13: I/O privilege level (2-bit field) */
#define FL_IOPL_SHIFT 12 /*         gates in/out and cli/sti for CPL > 0  */
#define FL_NT 0x00004000 /* bit 14: nested task — legacy hardware task    */
/*         switching; meaningless in long mode   */
#define FL_RF 0x00010000 /* bit 16: resume — suppress instruction         */
/*         breakpoints for one instruction       */
#define FL_VM 0x00020000 /* bit 17: virtual-8086 mode; unavailable in     */
/*         long mode                             */
#define FL_AC 0x00040000 /* bit 18: alignment check (with CR0.AM) —       */
/*         doubles as SMAP override via stac/clac*/
#define FL_VIF 0x00080000 /* bit 19: virtual interrupt flag (VME/PVI)      */
#define FL_VIP 0x00100000 /* bit 20: virtual interrupt pending             */
#define FL_ID 0x00200000 /* bit 21: writable iff CPUID is supported —     */
/*         the classic CPUID detection trick     */
/* Bits 3, 5, 15, 22-63 are reserved and read as 0 */

uint64_t irq_save(void);
void irq_restore(uint64_t flags);
uint64_t read_rflags(void);

#endif
